src/Entity/Visitor.php
<?php

namespace App\Entity;

use App\Repository\VisitorRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VisitorRepository::class)
 */
class Visitor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $ip_address;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $timestamp;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $page;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_logged_in;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIpAddress(): ?string
    {
        return $this->ip_address;
    }

    public function setIpAddress(string $ip_address): self
    {
        $this->ip_address = $ip_address;

        return $this;
    }

    public function getTimestamp(): ?string
    {
        return $this->timestamp;
    }

    public function setTimestamp(string $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    public function getPage(): ?string
    {
        return $this->page;
    }

    public function setPage(?string $page): self
    {
        $this->page = $page;

        return $this;
    }

    public function getIsLoggedIn(): ?bool
    {
        return $this->is_logged_in;
    }

    public function setIsLoggedIn(bool $is_logged_in): self
    {
        $this->is_logged_in = $is_logged_in;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Form/VisitorType.php
<?php

namespace App\Form;

use App\Entity\Visitor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VisitorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ip_address')
            ->add('timestamp')
            ->add('page')
            ->add('is_logged_in')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Visitor::class,
        ]);
    }
}

src/Controller/VisitorController.php
<?php

namespace App\Controller;

use App\Entity\Visitor;
use App\Form\VisitorType;
use App\Repository\VisitorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/visitor")
 */
class VisitorController extends AbstractController
{
    /**
     * @Route("/", name="app_visitor_index", methods={"GET"})
     */
    public function index(VisitorRepository $visitorRepository): Response
    {
        return $this->render('visitor/index.html.twig', [
            'visitors' => $visitorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_visitor_show", methods={"GET"})
     */
    public function show(Visitor $visitor): Response
    {
        return $this->render('visitor/show.html.twig', [
            'visitor' => $visitor,
        ]);
    }

    /**
     * @Route("/{id}", name="app_visitor_delete", methods={"POST"})
     */
    public function delete(Request $request, Visitor $visitor, VisitorRepository $visitorRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$visitor->getId(), $request->request->get('_token'))) {
            $visitorRepository->remove($visitor);
        }

        return $this->redirectToRoute('app_visitor_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/visitor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}visiteurs{% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1>visiteurs</h1>
    <div class="table-responsive">
    <table>
        <thead>
            <tr>
                {#<th>Ip address</th>#}
                <th>Timestamp</th>
                <th>Page</th>
                <th>Is logged in</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for visitor in visitors %}
            <tr>
               {# <td>{{ visitor.ipAddress }}</td>  #}
                <td>{{ visitor.timestamp }}</td>
                <td>{{ visitor.page }}</td>
                <td>{{ visitor.isLoggedIn ? 'Yes' : 'No' }}</td>
                <td class="buttons">
                    <a href="{{ path('app_visitor_show', {'id': visitor.id}) }}" class="btn-show" >Voir</a>
                    <form method="post" action="{{ path('app_visitor_delete', {'id': visitor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ visitor.id) }}">
                        <button class="btn-delete">Effacer</button>
                    </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    </div>
{% endblock %}

templates/visitor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}visiteurs{% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1>Visiteurs</h1>
    <div class="table-responsive">

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ visitor.id }}</td>
            </tr>
            <tr>
                {# <th>Ip address</th>
                <td>{{ visitor.ipAddress }}</td> #}
            </tr>
            <tr>
                <th>Timestamp</th>
                <td>{{ visitor.timestamp }}</td>
            </tr>
            <tr>
                <th>Page</th>
                <td>{{ visitor.page }}</td>
            </tr>
            <tr>
                <th>Is logged in</th>
                <td>{{ visitor.isLoggedIn ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ visitor.email }}</td>
            </tr>
        </tbody>
    </table>

    <a class="button-back" href="{{ path('app_visitor_index') }}">back to list</a>

    <form method="post" action="{{ path('app_visitor_delete', {'id': visitor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ visitor.id) }}">
        <button class="btn">Effacer</button>
    </form>
</div>
</div>
{% endblock %}